<% database_name = "ipga" %>

defaults: &defaults
  adapter: mysql
  username: root
  password: password
  host: localhost

development:
  database: <%= database_name %>_development
  <<: *defaults

test:
  database: <%= database_name %>_test
  <<: *defaults

production:
  database: ipga
  adapter: mysql
  username: ipga
  password: Advantage2009
  host: ipga.db.4481230.hostedresource.com

